# Generated by Django 4.2.7 on 2025-04-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisitions', '0001_add_pedido_entregue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_estudante', models.CharField(max_length=45)),
                ('matricula', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('bolsista_paae', models.BooleanField(default=False)),
                ('curso', models.CharField(choices=[('Computação', 'Informática'), ('Elétrica', 'Eletrotécnica'), ('Superior - Computação', 'Superior - Computação'), ('Superior - Matemática', 'Superior - Matemática')], max_length=50)),
                ('deseja_caderno', models.BooleanField(default=False)),
                ('deseja_garrafa', models.BooleanField(default=False)),
                ('deseja_camisa', models.BooleanField(default=False)),
                ('tamanho_camisa', models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=2, null=True)),
                ('pedido_entregue', models.BooleanField(default=False, verbose_name='Pedido Entregue')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
