# Generated by Django 4.2.7 on 2025-04-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
