# Generated by Django 5.1.7 on 2025-03-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_remove_estudante_data_estudante_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='bolsista_pae',
            new_name='bolsista_paae',
        ),
    ]
