# Generated by Django 4.2.7 on 2025-04-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_estudante_data_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='data_entrega',
            new_name='data_entrega_caderno',
        ),
        migrations.AddField(
            model_name='estudante',
            name='data_entrega_camisa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='data_entrega_garrafa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='data_entrega_sapato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
