# Generated by Django 5.1.7 on 2025-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_rename_bolsista_pae_estudante_bolsista_paae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequisicao',
            name='material',
        ),
        migrations.RemoveField(
            model_name='itemrequisicao',
            name='requisicao',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='estudante',
        ),
        migrations.AlterField(
            model_name='estudante',
            name='bolsista_paae',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ItemRequisicao',
        ),
        migrations.DeleteModel(
            name='Requisicao',
        ),
    ]
