# Generated by Django 5.1.7 on 2025-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0004_remove_itemrequisicao_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='camisa',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='curso',
            field=models.CharField(choices=[('Computação', 'Computação'), ('Elétrica', 'Eletrotécnica'), ('Superior - Computação', 'Superior - Computação'), ('Superior - Matemática', 'Superior - Matemática')], max_length=50),
        ),
    ]
