# Generated by Django 4.2.7 on 2025-04-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0004_rename_data_entrega_estudante_data_entrega_caderno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='deseja_sapato',
            field=models.BooleanField(default=False),
        ),
    ]
