# Generated by Django 5.1.7 on 2025-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0005_alter_estudante_camisa_alter_estudante_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='camisa',
        ),
        migrations.AddField(
            model_name='estudante',
            name='deseja_camisa',
            field=models.BooleanField(default=False, verbose_name='Deseja Camisa?'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='bolsista_paae',
            field=models.BooleanField(default=False, verbose_name='Bolsista PAAE?'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='curso',
            field=models.CharField(choices=[('Computação', 'Informática'), ('Elétrica', 'Eletrotécnica'), ('Superior - Computação', 'Superior - Computação'), ('Superior - Matemática', 'Superior - Matemática')], max_length=50),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='deseja_caderno',
            field=models.BooleanField(default=False, verbose_name='Deseja Caderno?'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='deseja_garrafa',
            field=models.BooleanField(default=False, verbose_name='Deseja Garrafa?'),
        ),
    ]
