# Generated by Django 5.1.7 on 2025-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0006_remove_estudante_camisa_estudante_deseja_camisa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='bolsista_paae',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='deseja_caderno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='deseja_camisa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='deseja_garrafa',
            field=models.BooleanField(default=False),
        ),
    ]
